export interface Company {
  id: string;
  name: string;
  logo: string;
  description: string;
  industry: string;
  location: string;
  careerUrl: string;
  openPositions: number;
  rating: number;
  featured: boolean;
}

export const companiesData: Company[] = [
  {
    id: '1',
    name: 'Google',
    logo: '/google-logo.png',
    description: 'Leading technology company specializing in internet-related services and products.',
    industry: 'Technology',
    location: 'Mountain View, CA',
    careerUrl: 'https://careers.google.com',
    openPositions: 1247,
    rating: 4.5,
    featured: true,
  },
  {
    id: '2',
    name: 'Microsoft',
    logo: '/microsoft-logo.png',
    description: 'Global technology company that develops, manufactures, licenses, and supports software products.',
    industry: 'Technology',
    location: 'Redmond, WA',
    careerUrl: 'https://careers.microsoft.com',
    openPositions: 892,
    rating: 4.3,
    featured: true,
  },
  {
    id: '3',
    name: 'Apple',
    logo: '/apple-logo.png',
    description: 'Multinational technology company that designs, develops, and sells consumer electronics.',
    industry: 'Technology',
    location: 'Cupertino, CA',
    careerUrl: 'https://jobs.apple.com',
    openPositions: 567,
    rating: 4.4,
    featured: true,
  },
  {
    id: '4',
    name: 'Amazon',
    logo: '/amazon-logo.png',
    description: 'Multinational technology company focusing on e-commerce, cloud computing, and AI.',
    industry: 'Technology',
    location: 'Seattle, WA',
    careerUrl: 'https://www.amazon.jobs',
    openPositions: 2341,
    rating: 4.1,
    featured: true,
  },
  {
    id: '5',
    name: 'Meta',
    logo: '/meta-logo.png',
    description: 'Technology company that builds products to help people connect and share.',
    industry: 'Technology',
    location: 'Menlo Park, CA',
    careerUrl: 'https://www.metacareers.com',
    openPositions: 756,
    rating: 4.2,
    featured: false,
  },
  {
    id: '6',
    name: 'Netflix',
    logo: '/netflix-logo.png',
    description: 'Entertainment company that provides streaming media and video-on-demand online.',
    industry: 'Entertainment',
    location: 'Los Gatos, CA',
    careerUrl: 'https://jobs.netflix.com',
    openPositions: 234,
    rating: 4.6,
    featured: false,
  },
  {
    id: '7',
    name: 'Tesla',
    logo: '/tesla-logo.png',
    description: 'Electric vehicle and clean energy company.',
    industry: 'Automotive',
    location: 'Austin, TX',
    careerUrl: 'https://www.tesla.com/careers',
    openPositions: 445,
    rating: 4.0,
    featured: false,
  },
  {
    id: '8',
    name: 'Spotify',
    logo: '/spotify-logo.png',
    description: 'Audio streaming and media services provider.',
    industry: 'Entertainment',
    location: 'Stockholm, Sweden',
    careerUrl: 'https://jobs.spotify.com',
    openPositions: 123,
    rating: 4.3,
    featured: false,
  },
  {
    id: '9',
    name: 'Uber',
    logo: '/uber-logo.png',
    description: 'Mobility and delivery platform connecting riders and drivers.',
    industry: 'Transportation',
    location: 'San Francisco, CA',
    careerUrl: 'https://www.uber.com/careers',
    openPositions: 678,
    rating: 3.9,
    featured: false,
  },
  {
    id: '10',
    name: 'Airbnb',
    logo: '/airbnb-logo.png',
    description: 'Online marketplace for lodging, primarily homestays for vacation rentals.',
    industry: 'Travel',
    location: 'San Francisco, CA',
    careerUrl: 'https://careers.airbnb.com',
    openPositions: 234,
    rating: 4.2,
    featured: false,
  },
  {
    id: '11',
    name: 'Stripe',
    logo: '/stripe-logo.png',
    description: 'Technology company that builds economic infrastructure for the internet.',
    industry: 'Fintech',
    location: 'San Francisco, CA',
    careerUrl: 'https://stripe.com/jobs',
    openPositions: 156,
    rating: 4.4,
    featured: false,
  },
  {
    id: '12',
    name: 'Salesforce',
    logo: '/salesforce-logo.png',
    description: 'Cloud-based software company that provides customer relationship management services.',
    industry: 'Technology',
    location: 'San Francisco, CA',
    careerUrl: 'https://salesforce.wd1.myworkdayjobs.com',
    openPositions: 892,
    rating: 4.1,
    featured: false,
  },
]; 